### PR TITLE
Adds ability to save presets from command interface

### PR DESCRIPTION
**Pull request by riban-bw**
Adds -P command line option to define default path where to save presets.
Adds "save preset" command.
Note: qt does not have command line parameters implemented.

### CODE REVIEW

**Comment by riban-bw** [comment]
Adds a command line parameter to jalv and jalv.gtk: -P <path to presets> which defines the default path that presets will be saved when the command "save preset" is called. The default is `./lv2` and it can be overriden with optional parameter to the "save preset" command.

Adds a console command: "save preset" which takes the mandatory parameter "label". This is what the preset will be called. Optional parameters:
- path - the path where the preset will be saved (default defined by -P command line parameter)
- filename.ttl - name of ttl file (including extension) to save this preset within (default <label>.ttl)
- uri - URI for the preset (default none)

With this change we can save presets via command interface, not just the GUI host.

Note that jalv.qt* does not implement command line parameters hence is missing the -P option and default path. This is not tested.

**Comment by jofemodo** [comment]
I'm using "current working dir" for saving presets from native GUI. Check this commit:

https://github.com/zynthian/jalv/commit/27a8be88572e1b1a0f78d6d026c7ba239fa0729e

and it's already implemented in zynthian_engine_jalv class:

https://github.com/zynthian/zynthian-ui/blob/4268fb198724b9f0d676153feae22793e613b72c/zyngine/zynthian_engine_jalv.py#L208

Please, let's stick to this as it works pretty nicely and we avoid adding a new CL option. Remember that all this changes should be merged upstream, so please, let's try to make "minimal changes" with the same "coding style" that current code base, etc. (i know you know ;-D)

**Comment by jofemodo** [comment]
Ahhh! Please, note how the plugin is reloaded into the lv2 world after saving the preset:

https://github.com/zynthian/jalv/blob/27a8be88572e1b1a0f78d6d026c7ba239fa0729e/src/jalv_gtk.c#L447

this is needed for rebuilding the preset list and allowing the new preset to be loaded. Note also that the plugin instance remains untouched.

I'm not sure we need this on the "cli" program, but we would need it, for sure, in the "gtk" one.

**Comment by polluxsynth** [comment]
Not critical in any way, but regarding the -P option I would say that even if in Zynthian it's easy to start jalv from the appropriate directory, for other (non-Zynthian) uses it may be practical not to have to do that and instead specify a directory on the command line, so it could be a worthwhile addition anyway.

**Comment by jofemodo** [comment]
I don't see a big difference between running this:

(cd /current/working/dir && jalv pluginmolon)

and this:

jalv -P /current/working/dir pluginmolon

from command line. 

But IMHO, the first way is more unix-like and it works for every command/program. It's the standard way and i don't need to read the jalv's man page for knowing what it means or how to do it.  We shouldn't add extra options for doing things that the operating system already implements in a well-known and consistent way.

Also, we would like to see our changes merged upstream, so we should avoid modifying more than strictly needed while trying to stick standards when they exist.

Regards

**Comment by polluxsynth** [comment]
Well, it's not something I feel it's worth arguing too much about. You certainly have a point, and making as few changes as possible upstream is certainly important, as obviously the need to have a -P option has not been an issue there.

In general though, I feel that programs that refer to CWD are mostly of the interactive sort such as an editor like vi or emacs, or git, where the user is working with different sets of files depending on the CWD, whereas applications that need to refer to configuration files or a directory hierarchy which is constant over several invocations usually have a default place for it (such as ~/.foo, or /usr/share/foo), which can then be overridden with a command line option or environment variable if need be. In the Zynthian case, since the user never needs to issue commands manually, this is not an issue anyway though, and it's certainly easier, once implemented, to change the CWD to the appropriate value, rather than having to keep track of different command line options for different programs.

**Comment by jofemodo** [comment]
Hi @riban-bw !

I merged your changes in a separated branch with the same name you used in your fork: save-presets
Also, i gave you access to this repo, so you can commit your changes directly here.

Thanks!

**Comment by riban-bw** [comment]
I have done more on this. I have been offline and unable to commit. Will catch up later.

**Comment by jofemodo** [comment]
I've been working on this too ;-)

**Pull request merged**
